### ISSUE TITLE
How do I update certificate with the shell?

### ISSUE THREAD

**Issue by 3n-mb** [janmojzis/letsencryptshell#1]
I have created certificates, using letsencrypt shell. How do I update certificates? Should the same steps be used, as for creation, or, some other commands are needed? 
README.md talks only about certificate creation.

**Comment by janmojzis** [comment]
Hello,
for update You should skip the 'Registration step' and the rest is exactly same as for creation.
Namely:
domainchallenge {domain}
domainconfirm {domain}
certificateget {domain}

**Comment by 3n-mb** [comment]
Cool. I'll do that. Do update readme, though.
Thank you for a great tool.

**Comment by janmojzis** [comment]
README updated, and added few examples:
https://mojzis.com/software/letsencryptshell/examples.html
