### ISSUE TITLE
Does it support subjectAltName

### ISSUE THREAD

**Issue by gdamjan** [janmojzis/letsencryptshell#2]
Letsencrypt seems to support the subjectAltName extension to have a single certificate for several host names (i.e. www and no www). Is this possible to use with letsencryptshell?

https://community.letsencrypt.org/t/subjectaltname-certificates/100

**Comment by janmojzis** [comment]
Yes,
https://mojzis.com/software/letsencryptshell/examples.html
see the SAN example

**Comment by gdamjan** [comment]
Thanks, I don't know how I missed that (I guess I wasn't aware of the _SAN_ abbreviation)
